### ISSUE TITLE
Pangres with MySQL

### ISSUE THREAD

**Issue by tlallema** [tlallema/pangres_mysql#1]
@ThibTrip
Do you have any example on how to use upsert function with MySQl as you did with SQlite ?
I receive error message : "All indexed must be named" and do not understand why

**Comment by ThibTrip** [comment]
Hello @tlallema ! This error has nothing to do with MySQL. <code>pangres</code> requires all index levels (columns if you wish) to be named. Those indices are then used to update (or create) a table in your database. The index must be unique and non null (Postgres cannot handle nulls in indices, even if the index is unique).

I have made a [gist](https://gist.github.com/ThibTrip/3d2719f476a43c625e270eb69fd05df8) for you.

To verify that your index is unique you can do:

```python
df.index.is_unique # where df is your pandas DataFrame
```

To check which indices are duplicated you can do:

```python
df.loc[df.index.duplicated(keep=False),:] # where df is your pandas DataFrame (remember to change the 2 mentions of "df" if you use another variable name! 
```

I hope you'll be able to solve your problem and if you do you can close this issue :+1: . You can also post a detailled example (as close to what you do as you can while respecting privacy of course) if you're still having troubles.

**Comment by tlallema** [comment]
hello @ThibTrip ,
thanks I will have a look at your suggestions and come back to you if needed.

**Comment by ThibTrip** [comment]
Oh I notice I wrote postgres by habit when I said the index should not be null but yeah it's the [same thing for MySQL](https://stackoverflow.com/a/11001408)
